#!/usr/bin/env python3
"""Generate a distilled PROJECT-MAP.md (~1.5-2K tokens) from a graphify graph.

Run from the project root (or pass --graph/--out explicitly). Stdlib only.
Reads graphify-out/graph.json (+ optional .graphify_labels.json next to it)
and writes a compact markdown map: corpus stats, god nodes, top communities
with member files, and top-level layout. Designed to be read by an AI at
session start instead of grepping the whole tree.
"""

import argparse
import json
import os
from collections import Counter, defaultdict
from pathlib import Path


def load_graph(graph_path: Path):
    with open(graph_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    nodes = data.get("nodes", [])
    links = data.get("links", [])
    hyperedges = data.get("hyperedges", [])
    labels_path = graph_path.parent / ".graphify_labels.json"
    labels = {}
    if labels_path.exists():
        with open(labels_path, "r", encoding="utf-8") as f:
            raw = json.load(f)
        for k, v in raw.items():
            try:
                labels[int(k)] = v
            except (ValueError, TypeError):
                continue
    return data, nodes, links, hyperedges, labels


def degree_ranking(nodes, links):
    by_id = {}
    for n in nodes:
        by_id[n["id"]] = n
    deg = Counter()
    for e in links:
        deg[e.get("source")] += 1
        deg[e.get("target")] += 1
    ranked = []
    for nid, d in deg.items():
        n = by_id.get(nid)
        if n is None:
            continue
        ranked.append((d, n))
    ranked.sort(key=lambda x: -x[0])
    return ranked


def community_members(nodes):
    groups = defaultdict(list)
    for n in nodes:
        groups[n.get("community")].append(n)
    return groups


def top_level_layout(nodes):
    counts = Counter()
    for n in nodes:
        if n.get("file_type") != "code" or not n.get("source_file"):
            continue
        top = Path(n["source_file"].replace("\\", "/")).parts[0]
        counts[top] += 1
    return counts.most_common()


def build_map(data, nodes, links, hyperedges, labels, args):
    project = Path(args.project).resolve().name or os.path.basename(os.getcwd())
    code_nodes = [n for n in nodes if n.get("file_type") == "code"]
    doc_nodes = [n for n in nodes if n.get("file_type") != "code"]
    ranked = degree_ranking(nodes, links)
    groups = community_members(nodes)
    layout = top_level_layout(nodes)

    lines = []
    add = lines.append

    add(f"# {project} — Project Map")
    add("")
    add("_Generated by graphify. Read this first before exploring the codebase; "
        "use the graphify MCP tools (query_graph / get_node / get_neighbors / "
        "god_nodes) for targeted lookups instead of grepping._")
    add("")
    add("## Corpus")
    add("")
    add(f"- {len(nodes)} nodes ({len(code_nodes)} code, {len(doc_nodes)} non-code), "
        f"{len(links)} edges, {len(hyperedges)} hyperedges")
    if layout:
        top = ", ".join(f"{d} ({c})" for d, c in layout[:12])
        add(f"- Top-level layout: {top}")
    add("")

    add("## God nodes (most connected — architectural hubs)")
    add("")
    for d, n in ranked[: args.top_gods]:
        src = n.get("source_file") or n.get("label") or n.get("id")
        add(f"- **{n.get('label', n.get('id'))}** — {d} links (`{src}`)")
    add("")

    add(f"## Top {args.top_communities} communities")
    add("")
    sorted_groups = sorted(groups.items(), key=lambda kv: -len(kv[1]))
    shown = 0
    for cid, members in sorted_groups:
        if shown >= args.top_communities:
            break
        shown += 1
        label = labels.get(cid, f"Community {cid}")
        samples = []
        seen = set()
        for m in members:
            if len(samples) >= args.max_members:
                break
            src = m.get("source_file") or m.get("label") or m.get("id")
            if src in seen:
                continue
            seen.add(src)
            samples.append(src)
        more = f", +{len(members) - args.max_members} more" if len(members) > args.max_members else ""
        add(f"### {label} ({len(members)} nodes)")
        add("")
        add(", ".join(samples) + more)
        add("")

    estimate = len("\n".join(lines)) // 4
    add(f"_(≈{estimate} tokens — cheap to read in full)_")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--project", default=os.getcwd(), help="project root (default: cwd)")
    ap.add_argument("--graph", default=None, help="path to graph.json (default: <project>/graphify-out/graph.json)")
    ap.add_argument("--out", default=None, help="output path (default: <project>/graphify-out/PROJECT-MAP.md)")
    ap.add_argument("--top-gods", type=int, default=10)
    ap.add_argument("--top-communities", type=int, default=10)
    ap.add_argument("--max-members", type=int, default=6)
    args = ap.parse_args()

    project = Path(args.project).resolve()
    graph_path = Path(args.graph) if args.graph else project / "graphify-out" / "graph.json"
    out_path = Path(args.out) if args.out else project / "graphify-out" / "PROJECT-MAP.md"

    if not graph_path.exists():
        raise SystemExit(f"ERROR: graph not found at {graph_path} — run /graphify or graphify extract first")

    data, nodes, links, hyperedges, labels = load_graph(graph_path)
    args.project = str(project)
    text = build_map(data, nodes, links, hyperedges, labels, args)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"Wrote {out_path} ({len(text)} chars, ~{len(text) // 4} tokens)")


if __name__ == "__main__":
    main()
